services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    hostname: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: ${ORACLE_PWD}
    volumes:
      - ${DB_DATA_PATH}/oradata:/opt/oracle/oradata
    restart: always
