-- 0010: BOM 테이블 생성 (자재 레시피 및 투입 공정 매핑)
CREATE TABLE BOM (
    bom_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_item_id NUMBER NOT NULL,
    child_item_id NUMBER NOT NULL,
    step_id NUMBER NOT NULL,
    bom_qty NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_BOM_PARENT FOREIGN KEY (parent_item_id) REFERENCES ITEM(item_id),
    CONSTRAINT FK_BOM_CHILD FOREIGN KEY (child_item_id) REFERENCES ITEM(item_id),
    CONSTRAINT FK_BOM_STEP FOREIGN KEY (step_id) REFERENCES PROCESS_STEP(step_id),
    CONSTRAINT UQ_BOM_ITEM_STEP UNIQUE (parent_item_id, child_item_id, step_id)
);
/
