-- 0027: Lot genealogy and creation source trace
CREATE TABLE LOT_TRACE (
    lot_trace_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_lot_id NUMBER,
    child_lot_id NUMBER NOT NULL,
    trace_type VARCHAR2(50) NOT NULL,
    input_qty NUMBER,
    output_qty NUMBER DEFAULT 0 NOT NULL,
    process_step_execution_id NUMBER,
    ref_type VARCHAR2(50),
    ref_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_LOT_TRACE_PARENT_LOT FOREIGN KEY (parent_lot_id) REFERENCES LOT(lot_id),
    CONSTRAINT FK_LOT_TRACE_CHILD_LOT FOREIGN KEY (child_lot_id) REFERENCES LOT(lot_id),
    CONSTRAINT FK_LOT_TRACE_EXECUTION FOREIGN KEY (process_step_execution_id) REFERENCES PROCESS_STEP_EXECUTION(process_step_execution_id),
    CONSTRAINT CHK_LOT_TRACE_INPUT_QTY CHECK (input_qty IS NULL OR input_qty >= 0),
    CONSTRAINT CHK_LOT_TRACE_OUTPUT_QTY CHECK (output_qty >= 0)
);
/
